image:
  file: .gitpod.Dockerfile

ports:
  - port: 8000
    onOpen: open-browser
  - port: 3000
    onOpen: open-browser
  - port: 5432
    onOpen: ignore
tasks:
  - init: >
      python script_setup_django.py
  - command: >
      echo Terminal 1 &&
      pipenv shell &&
      echo "from backend.settings import *" > backend/local_settings.py &&
      echo "ALLOWED_HOST" = ['*'] >> backend/local_settings.py &&
      export DJANGO_SETTINGS_MODULE=backend.localsettings &&
      python manage.py runserver 0.0.0.0:8000
      name: Django Server
  - command: >
      echo Terminal 2 &&
      cd frontend && yarn start &&
      name: React Server
