image:
  file: .gitpod.Dockerfile

tasks:
  - init: pipenv sync
    command: 
      pipenv shell
      echo DATABASE_URL=$DATABASE_URL >> .env
      pg_start.sh
      psql -f setups/database-setup.sql
ports:
  - port: 8000

