version: '3.8'

services:
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    command: python mange.py runserver 0.0.0.0:8000
    volumes:
      -  ./web/:/user/src/web
    ports:
      - 8000:8000
      - 3000:3000
      - 35729:35729
    env_file:
    - ./env.dev
    stdin_open: true
    depends_on:
    - db
  
  db:
    container_name: database
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=dev

volumes:
  postgres_data:
